### ISSUE TITLE
ActiveModel::MissingAttributeError: can't write unknown attribute `tags`

### ISSUE THREAD

**Issue by itay-grudev** [zdennis/activerecord-import#497]
I am encountering this strange issue on my production server which I cannot understand.

On my side of the code I have the following:

```ruby
Whatever.import whatevers, on_duplicate_key_update: {
  columns: WHATEVER_FIELDS - [
    :id, :description, :created_at, :updated_at, :image, :tags
  ]
}
```

```ruby
ActiveModel::MissingAttributeError: can't write unknown attribute `tags`
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/attribute.rb:182:in `with_value_from_database'
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/attribute_set.rb:53:in `write_from_user'
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/attribute_methods/write.rb:50:in `write_attribute_with_type_cast'
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/attribute_methods/write.rb:32:in `write_attribute'
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.6/lib/active_record/attribute_methods.rb:361:in `[]='
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-import-0.22.0/lib/activerecord-import/import.rb:647:in `block (2 levels) in import_with_validations'
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-import-0.22.0/lib/activerecord-import/import.rb:647:in `each_pair'
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-import-0.22.0/lib/activerecord-import/import.rb:647:in `block in import_with_validations'
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-import-0.22.0/lib/activerecord-import/import.rb:645:in `each'
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-import-0.22.0/lib/activerecord-import/import.rb:645:in `each_with_index'
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-import-0.22.0/lib/activerecord-import/import.rb:645:in `import_with_validations'
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-import-0.22.0/lib/activerecord-import/import.rb:602:in `import_helper'
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/activerecord-import-0.22.0/lib/activerecord-import/import.rb:458:in `import'
/home/deploy/app/releases/20180202184724/lib/tasks/data.rake:244:in `block (2 levels) in <top (required)>'
/home/deploy/app/shared/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/deploy/.rvm/gems/ruby-2.3.4/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.3.4/bin/bundle:23:in `load'
/home/deploy/.rvm/gems/ruby-2.3.4/bin/bundle:23:in `<main>'
/home/deploy/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/home/deploy/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => data:import
(See full trace by running task with --trace)
```

**Comment by jkowens** [comment]
Also, can you try running the import without `:on_duplicate_key_update` so we can try to see if it is related to the error or not? Looking at your stacktrace I'm starting to think it's unrelated. We might need more info about the `Whatever` model. The types of attributes, etc. Are `tags` some type of serialized field?

**Comment by jkowens** [comment]
Try connecting to your production database and confirming that the `tags` column is actually there.

**Comment by itay-grudev** [comment]
You are correct. There was an inconsistency in the migrations ran on our staging and our production server and the column was indeed missing.
